import json

iteration = 1

fileNames = input('Give filenames (Seperated by comma, exclude extension)\n> ').split(',')
filePaths = []
fileJsons = []

for fileName in fileNames:
        filePaths.append(fileName + '.json')

for file in filePaths:
        jsonFile = open(file, 'r')
        jsonData = json.load(jsonFile)
        fileJsons.append(jsonData)

finalJson = ''    

for data in fileJsons:
        finalJson += ('# '+data['title']+' ('+data['date']+')\n'+data['content'] + '\n\n')

finalJson += 'Generated by Blog Writer Iteration '+str(iteration)
       
print('Copy this: ') 
print(finalJson)