import json, sys

iteration = 3

folder = ''

fileNames = []
filePaths = []
fileJsons = []

if sys.argv.__len__() < 2:
        folder = input('What folder are these files in? (leave blank if no folder)\n> ')
        fileNames = input('Give filenames (Seperated by comma, exclude extension)\n> ').split(',')
else:
        folder = sys.argv[1]
        fileNames = sys.argv[2].split(',')


if folder.__len__() > 0:
        folder += '/'

for fileName in fileNames:
        filePaths.append(folder + fileName + '.json')

for file in filePaths:
        jsonFile = open(file, 'r')
        jsonData = json.load(jsonFile)
        fileJsons.append(jsonData)

finalJson = ''    

for data in fileJsons:
        finalJson += ('# '+data['title']+' ('+data['date']+')\n'+data['content'] + '\n\n')

finalJson += 'Generated by Blog Writer Iteration '+str(iteration)

print('\n\nPaths: ') 
for path in filePaths:
        print('* ' + path)
print('\n\nCopy this: ') 
print(finalJson)